### ISSUE TITLE
Imported .STL object disappearing when adding emitter

### ISSUE THREAD

**Issue by mgomez0** [natecraddock/projectile#13]
Hi Nate,

I'm currently working on animating a lunar landing, and this tool seems perfect for what I'm trying to accomplish, as the lander will be at specific velocities at specific times. However, the lander itself is a .stl file I imported into my scene. When I try to add an emitter to the lander, the lander disappears completely and I just see the point-emitter itself. I tried to add an emitter to a Blender built-in monkey head, and it works perfectly. Any pointers? 

Thank you,
Michael

**Comment by natecraddock** [comment]
Hey @mgomez0, sorry for the issues. I'm not quite sure why an imported .stl file would have issues, since the import process would convert it to a normal object. Is there a chance you could attach the file so I could test? That would make any necessary fixes easier.

**Comment by mgomez0** [comment]
The lander model is too large to send through here, even zipped it is still 82 MB, but I have another .stl file I can send you that is exhibiting the same behavior. Also, since this is a full-scale mechanical model, I scaled it down to 0.001 on all axes to make it reasonable to work with in Blender. Not sure if this has any impact.
[payload.zip](https://github.com/natecraddock/projectile/files/4524167/payload.zip)

**Comment by natecraddock** [comment]
Thanks, that will help a lot. I'll take a look later today and try to get it fixed!

**Comment by natecraddock** [comment]
Okay I got it to work properly with the sample .STL file. Have you applied scale after scaling the model down (<kbd>Ctrl + A</kbd> `> Scale` or `Object > Apply > Scale`)? After doing that everything worked properly for me.

Also, you will want to do `Object > Set Origin > Origin to Center of Mass` if the imported object does not have a proper origin.

As an aside because you are doing a lunar landing you might find it useful to lower the scene gravity in Blender. Projectile will automatically adjust the trajectory to use the new gravity.

**Comment by mgomez0** [comment]
Applying the scale and setting the origin seemed to have done the trick!! Thank you so much for the help, I'm still very new to Blender. I'm way more of a programmer and engineer than an artist but integrating Python and tools like yours make it a joy to work with. Thanks again!

**Comment by natecraddock** [comment]
@mgomez0 You're welcome! I'm glad you like it. If you are able to, I would enjoy seeing your animation when it is finished
